//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2ContactManager : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2ContactManager(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2ContactManager obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2ContactManager() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2ContactManager(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2ContactManager() : this(Box2DPINVOKE.new_b2ContactManager(), true) {
  }

  public void AddPair(SWIGTYPE_p_void proxyUserDataA, SWIGTYPE_p_void proxyUserDataB) {
    Box2DPINVOKE.b2ContactManager_AddPair(swigCPtr, SWIGTYPE_p_void.getCPtr(proxyUserDataA), SWIGTYPE_p_void.getCPtr(proxyUserDataB));
  }

  public void FindNewContacts() {
    Box2DPINVOKE.b2ContactManager_FindNewContacts(swigCPtr);
  }

  public void Destroy(b2Contact c) {
    Box2DPINVOKE.b2ContactManager_Destroy(swigCPtr, b2Contact.getCPtr(c));
  }

  public void Collide() {
    Box2DPINVOKE.b2ContactManager_Collide(swigCPtr);
  }

  public b2BroadPhase m_broadPhase {
    set {
      Box2DPINVOKE.b2ContactManager_m_broadPhase_set(swigCPtr, b2BroadPhase.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2ContactManager_m_broadPhase_get(swigCPtr);
      b2BroadPhase ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2BroadPhase(cPtr, false);
      return ret;
    } 
  }

  public b2Contact m_contactList {
    set {
      Box2DPINVOKE.b2ContactManager_m_contactList_set(swigCPtr, b2Contact.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2ContactManager_m_contactList_get(swigCPtr);
      b2Contact ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Contact(cPtr, false);
      return ret;
    } 
  }

  public int m_contactCount {
    set {
      Box2DPINVOKE.b2ContactManager_m_contactCount_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2ContactManager_m_contactCount_get(swigCPtr);
      return ret;
    } 
  }

  public b2ContactFilter m_contactFilter {
    set {
      Box2DPINVOKE.b2ContactManager_m_contactFilter_set(swigCPtr, b2ContactFilter.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2ContactManager_m_contactFilter_get(swigCPtr);
      b2ContactFilter ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2ContactFilter(cPtr, false);
      return ret;
    } 
  }

  public b2ContactListener m_contactListener {
    set {
      Box2DPINVOKE.b2ContactManager_m_contactListener_set(swigCPtr, b2ContactListener.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2ContactManager_m_contactListener_get(swigCPtr);
      b2ContactListener ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2ContactListener(cPtr, false);
      return ret;
    } 
  }

  public b2BlockAllocator m_allocator {
    set {
      Box2DPINVOKE.b2ContactManager_m_allocator_set(swigCPtr, b2BlockAllocator.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2ContactManager_m_allocator_get(swigCPtr);
      b2BlockAllocator ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2BlockAllocator(cPtr, false);
      return ret;
    } 
  }

}

}
