//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2Color : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Color(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Color obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Color() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Color(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2Color() : this(Box2DPINVOKE.new_b2Color__SWIG_0(), true) {
  }

  public b2Color(float rIn, float gIn, float bIn, float aIn) : this(Box2DPINVOKE.new_b2Color__SWIG_1(rIn, gIn, bIn, aIn), true) {
  }

  public b2Color(float rIn, float gIn, float bIn) : this(Box2DPINVOKE.new_b2Color__SWIG_2(rIn, gIn, bIn), true) {
  }

  public void Set(float rIn, float gIn, float bIn, float aIn) {
    Box2DPINVOKE.b2Color_Set__SWIG_0(swigCPtr, rIn, gIn, bIn, aIn);
  }

  public void Set(float rIn, float gIn, float bIn) {
    Box2DPINVOKE.b2Color_Set__SWIG_1(swigCPtr, rIn, gIn, bIn);
  }

  public float r {
    set {
      Box2DPINVOKE.b2Color_r_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Color_r_get(swigCPtr);
      return ret;
    } 
  }

  public float g {
    set {
      Box2DPINVOKE.b2Color_g_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Color_g_get(swigCPtr);
      return ret;
    } 
  }

  public float b {
    set {
      Box2DPINVOKE.b2Color_b_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Color_b_get(swigCPtr);
      return ret;
    } 
  }

  public float a {
    set {
      Box2DPINVOKE.b2Color_a_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Color_a_get(swigCPtr);
      return ret;
    } 
  }

}

}
