//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2FixtureDef : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2FixtureDef(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2FixtureDef obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2FixtureDef() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2FixtureDef(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2FixtureDef() : this(Box2DPINVOKE.new_b2FixtureDef(), true) {
  }

  public b2Shape shape {
    set {
      Box2DPINVOKE.b2FixtureDef_shape_set(swigCPtr, b2Shape.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_shape_get(swigCPtr);
      b2Shape ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Shape(cPtr, false);
      return ret;
    } 
  }

  public SWIGTYPE_p_void userData {
    set {
      Box2DPINVOKE.b2FixtureDef_userData_set(swigCPtr, SWIGTYPE_p_void.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_userData_get(swigCPtr);
      SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
      return ret;
    } 
  }

  public float friction {
    set {
      Box2DPINVOKE.b2FixtureDef_friction_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_friction_get(swigCPtr);
      return ret;
    } 
  }

  public float restitution {
    set {
      Box2DPINVOKE.b2FixtureDef_restitution_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_restitution_get(swigCPtr);
      return ret;
    } 
  }

  public float density {
    set {
      Box2DPINVOKE.b2FixtureDef_density_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2FixtureDef_density_get(swigCPtr);
      return ret;
    } 
  }

  public bool isSensor {
    set {
      Box2DPINVOKE.b2FixtureDef_isSensor_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2FixtureDef_isSensor_get(swigCPtr);
      return ret;
    } 
  }

  public b2Filter filter {
    set {
      Box2DPINVOKE.b2FixtureDef_filter_set(swigCPtr, b2Filter.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2FixtureDef_filter_get(swigCPtr);
      b2Filter ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Filter(cPtr, false);
      return ret;
    } 
  }

}

}
