//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2Filter : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Filter(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Filter obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Filter() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Filter(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2Filter() : this(Box2DPINVOKE.new_b2Filter(), true) {
  }

  public ushort categoryBits {
    set {
      Box2DPINVOKE.b2Filter_categoryBits_set(swigCPtr, value);
    } 
    get {
      ushort ret = Box2DPINVOKE.b2Filter_categoryBits_get(swigCPtr);
      return ret;
    } 
  }

  public ushort maskBits {
    set {
      Box2DPINVOKE.b2Filter_maskBits_set(swigCPtr, value);
    } 
    get {
      ushort ret = Box2DPINVOKE.b2Filter_maskBits_get(swigCPtr);
      return ret;
    } 
  }

  public short groupIndex {
    set {
      Box2DPINVOKE.b2Filter_groupIndex_set(swigCPtr, value);
    } 
    get {
      short ret = Box2DPINVOKE.b2Filter_groupIndex_get(swigCPtr);
      return ret;
    } 
  }

}

}
