//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2Joint : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Joint(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Joint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Joint() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          throw new global::System.MethodAccessException("C++ destructor does not have public access");
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2JointType GetType() {
    b2JointType ret = (b2JointType)Box2DPINVOKE.b2Joint_GetType(swigCPtr);
    return ret;
  }

  public b2Body GetBodyA() {
    global::System.IntPtr cPtr = Box2DPINVOKE.b2Joint_GetBodyA(swigCPtr);
    b2Body ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Body(cPtr, false);
    return ret;
  }

  public b2Body GetBodyB() {
    global::System.IntPtr cPtr = Box2DPINVOKE.b2Joint_GetBodyB(swigCPtr);
    b2Body ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Body(cPtr, false);
    return ret;
  }

  public virtual b2Vec2 GetAnchorA() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Joint_GetAnchorA(swigCPtr), true);
    return ret;
  }

  public virtual b2Vec2 GetAnchorB() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Joint_GetAnchorB(swigCPtr), true);
    return ret;
  }

  public virtual b2Vec2 GetReactionForce(float inv_dt) {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Joint_GetReactionForce(swigCPtr, inv_dt), true);
    return ret;
  }

  public virtual float GetReactionTorque(float inv_dt) {
    float ret = Box2DPINVOKE.b2Joint_GetReactionTorque(swigCPtr, inv_dt);
    return ret;
  }

  public b2Joint GetNext() {
    global::System.IntPtr cPtr = Box2DPINVOKE.b2Joint_GetNext__SWIG_0(swigCPtr);
    b2Joint ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Joint(cPtr, false);
    return ret;
  }

  public SWIGTYPE_p_void GetUserData() {
    global::System.IntPtr cPtr = Box2DPINVOKE.b2Joint_GetUserData(swigCPtr);
    SWIGTYPE_p_void ret = (cPtr == global::System.IntPtr.Zero) ? null : new SWIGTYPE_p_void(cPtr, false);
    return ret;
  }

  public void SetUserData(SWIGTYPE_p_void data) {
    Box2DPINVOKE.b2Joint_SetUserData(swigCPtr, SWIGTYPE_p_void.getCPtr(data));
  }

  public bool IsEnabled() {
    bool ret = Box2DPINVOKE.b2Joint_IsEnabled(swigCPtr);
    return ret;
  }

  public bool GetCollideConnected() {
    bool ret = Box2DPINVOKE.b2Joint_GetCollideConnected(swigCPtr);
    return ret;
  }

  public virtual void Dump() {
    Box2DPINVOKE.b2Joint_Dump(swigCPtr);
  }

  public virtual void ShiftOrigin(b2Vec2 newOrigin) {
    Box2DPINVOKE.b2Joint_ShiftOrigin(swigCPtr, b2Vec2.getCPtr(newOrigin));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public virtual void Draw(b2Draw draw) {
    Box2DPINVOKE.b2Joint_Draw(swigCPtr, b2Draw.getCPtr(draw));
  }

}

}
