//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2JointEdge : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2JointEdge(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2JointEdge obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2JointEdge() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2JointEdge(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2Body other {
    set {
      Box2DPINVOKE.b2JointEdge_other_set(swigCPtr, b2Body.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2JointEdge_other_get(swigCPtr);
      b2Body ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Body(cPtr, false);
      return ret;
    } 
  }

  public b2Joint joint {
    set {
      Box2DPINVOKE.b2JointEdge_joint_set(swigCPtr, b2Joint.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2JointEdge_joint_get(swigCPtr);
      b2Joint ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Joint(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge prev {
    set {
      Box2DPINVOKE.b2JointEdge_prev_set(swigCPtr, b2JointEdge.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2JointEdge_prev_get(swigCPtr);
      b2JointEdge ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2JointEdge(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge next {
    set {
      Box2DPINVOKE.b2JointEdge_next_set(swigCPtr, b2JointEdge.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2JointEdge_next_get(swigCPtr);
      b2JointEdge ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2JointEdge(cPtr, false);
      return ret;
    } 
  }

  public b2JointEdge() : this(Box2DPINVOKE.new_b2JointEdge(), true) {
  }

}

}
