//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public enum b2JointType {
  e_unknownJoint,
  e_revoluteJoint,
  e_prismaticJoint,
  e_distanceJoint,
  e_pulleyJoint,
  e_mouseJoint,
  e_gearJoint,
  e_wheelJoint,
  e_weldJoint,
  e_frictionJoint,
  e_ropeJoint,
  e_motorJoint
}

}
