//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public enum b2LimitState {
  e_inactiveLimit,
  e_atLowerLimit,
  e_atUpperLimit,
  e_equalLimits
}

}
