//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2PulleyJoint : b2Joint {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal b2PulleyJoint(global::System.IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2PulleyJoint_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2PulleyJoint obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2PulleyJoint(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public override b2Vec2 GetAnchorA() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2PulleyJoint_GetAnchorA(swigCPtr), true);
    return ret;
  }

  public override b2Vec2 GetAnchorB() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2PulleyJoint_GetAnchorB(swigCPtr), true);
    return ret;
  }

  public override b2Vec2 GetReactionForce(float inv_dt) {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2PulleyJoint_GetReactionForce(swigCPtr, inv_dt), true);
    return ret;
  }

  public override float GetReactionTorque(float inv_dt) {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetReactionTorque(swigCPtr, inv_dt);
    return ret;
  }

  public b2Vec2 GetGroundAnchorA() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2PulleyJoint_GetGroundAnchorA(swigCPtr), true);
    return ret;
  }

  public b2Vec2 GetGroundAnchorB() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2PulleyJoint_GetGroundAnchorB(swigCPtr), true);
    return ret;
  }

  public float GetLengthA() {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetLengthA(swigCPtr);
    return ret;
  }

  public float GetLengthB() {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetLengthB(swigCPtr);
    return ret;
  }

  public float GetRatio() {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetRatio(swigCPtr);
    return ret;
  }

  public float GetCurrentLengthA() {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetCurrentLengthA(swigCPtr);
    return ret;
  }

  public float GetCurrentLengthB() {
    float ret = Box2DPINVOKE.b2PulleyJoint_GetCurrentLengthB(swigCPtr);
    return ret;
  }

  public override void Dump() {
    Box2DPINVOKE.b2PulleyJoint_Dump(swigCPtr);
  }

  public override void ShiftOrigin(b2Vec2 newOrigin) {
    Box2DPINVOKE.b2PulleyJoint_ShiftOrigin(swigCPtr, b2Vec2.getCPtr(newOrigin));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
