//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2RevoluteJointDef : b2JointDef {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal b2RevoluteJointDef(global::System.IntPtr cPtr, bool cMemoryOwn) : base(Box2DPINVOKE.b2RevoluteJointDef_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2RevoluteJointDef obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2RevoluteJointDef(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public b2RevoluteJointDef() : this(Box2DPINVOKE.new_b2RevoluteJointDef(), true) {
  }

  public void Initialize(b2Body bodyA, b2Body bodyB, b2Vec2 anchor) {
    Box2DPINVOKE.b2RevoluteJointDef_Initialize(swigCPtr, b2Body.getCPtr(bodyA), b2Body.getCPtr(bodyB), b2Vec2.getCPtr(anchor));
    if (Box2DPINVOKE.SWIGPendingException.Pending) throw Box2DPINVOKE.SWIGPendingException.Retrieve();
  }

  public b2Vec2 localAnchorA {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_localAnchorA_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2RevoluteJointDef_localAnchorA_get(swigCPtr);
      b2Vec2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public b2Vec2 localAnchorB {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_localAnchorB_set(swigCPtr, b2Vec2.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2RevoluteJointDef_localAnchorB_get(swigCPtr);
      b2Vec2 ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Vec2(cPtr, false);
      return ret;
    } 
  }

  public float referenceAngle {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_referenceAngle_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RevoluteJointDef_referenceAngle_get(swigCPtr);
      return ret;
    } 
  }

  public bool enableLimit {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_enableLimit_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2RevoluteJointDef_enableLimit_get(swigCPtr);
      return ret;
    } 
  }

  public float lowerAngle {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_lowerAngle_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RevoluteJointDef_lowerAngle_get(swigCPtr);
      return ret;
    } 
  }

  public float upperAngle {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_upperAngle_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RevoluteJointDef_upperAngle_get(swigCPtr);
      return ret;
    } 
  }

  public bool enableMotor {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_enableMotor_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2RevoluteJointDef_enableMotor_get(swigCPtr);
      return ret;
    } 
  }

  public float motorSpeed {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_motorSpeed_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RevoluteJointDef_motorSpeed_get(swigCPtr);
      return ret;
    } 
  }

  public float maxMotorTorque {
    set {
      Box2DPINVOKE.b2RevoluteJointDef_maxMotorTorque_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2RevoluteJointDef_maxMotorTorque_get(swigCPtr);
      return ret;
    } 
  }

}

}
