//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2SolverData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2SolverData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2SolverData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2SolverData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2SolverData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2TimeStep step {
    set {
      Box2DPINVOKE.b2SolverData_step_set(swigCPtr, b2TimeStep.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2SolverData_step_get(swigCPtr);
      b2TimeStep ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2TimeStep(cPtr, false);
      return ret;
    } 
  }

  public b2Position positions {
    set {
      Box2DPINVOKE.b2SolverData_positions_set(swigCPtr, b2Position.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2SolverData_positions_get(swigCPtr);
      b2Position ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Position(cPtr, false);
      return ret;
    } 
  }

  public b2Velocity velocities {
    set {
      Box2DPINVOKE.b2SolverData_velocities_set(swigCPtr, b2Velocity.getCPtr(value));
    } 
    get {
      global::System.IntPtr cPtr = Box2DPINVOKE.b2SolverData_velocities_get(swigCPtr);
      b2Velocity ret = (cPtr == global::System.IntPtr.Zero) ? null : new b2Velocity(cPtr, false);
      return ret;
    } 
  }

  public b2SolverData() : this(Box2DPINVOKE.new_b2SolverData(), true) {
  }

}

}
