//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2StackEntry : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2StackEntry(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2StackEntry obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2StackEntry() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2StackEntry(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public string data {
    set {
      Box2DPINVOKE.b2StackEntry_data_set(swigCPtr, value);
    } 
    get {
      string ret = Box2DPINVOKE.b2StackEntry_data_get(swigCPtr);
      return ret;
    } 
  }

  public int size {
    set {
      Box2DPINVOKE.b2StackEntry_size_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2StackEntry_size_get(swigCPtr);
      return ret;
    } 
  }

  public bool usedMalloc {
    set {
      Box2DPINVOKE.b2StackEntry_usedMalloc_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2StackEntry_usedMalloc_get(swigCPtr);
      return ret;
    } 
  }

  public b2StackEntry() : this(Box2DPINVOKE.new_b2StackEntry(), true) {
  }

}

}
