//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2TimeStep : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2TimeStep(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2TimeStep obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2TimeStep() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2TimeStep(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public float dt {
    set {
      Box2DPINVOKE.b2TimeStep_dt_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_dt_get(swigCPtr);
      return ret;
    } 
  }

  public float inv_dt {
    set {
      Box2DPINVOKE.b2TimeStep_inv_dt_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_inv_dt_get(swigCPtr);
      return ret;
    } 
  }

  public float dtRatio {
    set {
      Box2DPINVOKE.b2TimeStep_dtRatio_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2TimeStep_dtRatio_get(swigCPtr);
      return ret;
    } 
  }

  public int velocityIterations {
    set {
      Box2DPINVOKE.b2TimeStep_velocityIterations_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TimeStep_velocityIterations_get(swigCPtr);
      return ret;
    } 
  }

  public int positionIterations {
    set {
      Box2DPINVOKE.b2TimeStep_positionIterations_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2TimeStep_positionIterations_get(swigCPtr);
      return ret;
    } 
  }

  public bool warmStarting {
    set {
      Box2DPINVOKE.b2TimeStep_warmStarting_set(swigCPtr, value);
    } 
    get {
      bool ret = Box2DPINVOKE.b2TimeStep_warmStarting_get(swigCPtr);
      return ret;
    } 
  }

  public b2TimeStep() : this(Box2DPINVOKE.new_b2TimeStep(), true) {
  }

}

}
