//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2Vec3 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Vec3(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Vec3 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Vec3() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Vec3(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2Vec3() : this(Box2DPINVOKE.new_b2Vec3__SWIG_0(), true) {
  }

  public b2Vec3(float xIn, float yIn, float zIn) : this(Box2DPINVOKE.new_b2Vec3__SWIG_1(xIn, yIn, zIn), true) {
  }

  public void SetZero() {
    Box2DPINVOKE.b2Vec3_SetZero(swigCPtr);
  }

  public void Set(float x_, float y_, float z_) {
    Box2DPINVOKE.b2Vec3_Set(swigCPtr, x_, y_, z_);
  }

  public float x {
    set {
      Box2DPINVOKE.b2Vec3_x_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      Box2DPINVOKE.b2Vec3_y_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_y_get(swigCPtr);
      return ret;
    } 
  }

  public float z {
    set {
      Box2DPINVOKE.b2Vec3_z_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec3_z_get(swigCPtr);
      return ret;
    } 
  }

}

}
