//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace b2Sharp {

public class b2Version : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Version(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Version obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Version() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Version(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public int major {
    set {
      Box2DPINVOKE.b2Version_major_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2Version_major_get(swigCPtr);
      return ret;
    } 
  }

  public int minor {
    set {
      Box2DPINVOKE.b2Version_minor_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2Version_minor_get(swigCPtr);
      return ret;
    } 
  }

  public int revision {
    set {
      Box2DPINVOKE.b2Version_revision_set(swigCPtr, value);
    } 
    get {
      int ret = Box2DPINVOKE.b2Version_revision_get(swigCPtr);
      return ret;
    } 
  }

  public b2Version() : this(Box2DPINVOKE.new_b2Version(), true) {
  }

}

}
