//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.2
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace Box2DCS {

public class b2Vec2 : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal b2Vec2(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(b2Vec2 obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~b2Vec2() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          Box2DPINVOKE.delete_b2Vec2(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public b2Vec2() : this(Box2DPINVOKE.new_b2Vec2__SWIG_0(), true) {
  }

  public b2Vec2(float xIn, float yIn) : this(Box2DPINVOKE.new_b2Vec2__SWIG_1(xIn, yIn), true) {
  }

  public void SetZero() {
    Box2DPINVOKE.b2Vec2_SetZero(swigCPtr);
  }

  public void Set(float x_, float y_) {
    Box2DPINVOKE.b2Vec2_Set(swigCPtr, x_, y_);
  }

  public float Length() {
    float ret = Box2DPINVOKE.b2Vec2_Length(swigCPtr);
    return ret;
  }

  public float LengthSquared() {
    float ret = Box2DPINVOKE.b2Vec2_LengthSquared(swigCPtr);
    return ret;
  }

  public float Normalize() {
    float ret = Box2DPINVOKE.b2Vec2_Normalize(swigCPtr);
    return ret;
  }

  public bool IsValid() {
    bool ret = Box2DPINVOKE.b2Vec2_IsValid(swigCPtr);
    return ret;
  }

  public b2Vec2 Skew() {
    b2Vec2 ret = new b2Vec2(Box2DPINVOKE.b2Vec2_Skew(swigCPtr), true);
    return ret;
  }

  public float x {
    set {
      Box2DPINVOKE.b2Vec2_x_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec2_x_get(swigCPtr);
      return ret;
    } 
  }

  public float y {
    set {
      Box2DPINVOKE.b2Vec2_y_set(swigCPtr, value);
    } 
    get {
      float ret = Box2DPINVOKE.b2Vec2_y_get(swigCPtr);
      return ret;
    } 
  }

}

}
